# Generated by Django 5.1 on 2024-09-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0007_alter_teacher_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], max_length=25)),
                ('document', models.FileField(upload_to='documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
    ]
