# Generated by Django 5.1.1 on 2024-09-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_task',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=25),
        ),
    ]
